### ISSUE TITLE
tc_tcp_003 is run twice in test_suite, looks suspiciois

### ISSUE THREAD

**Issue by pfalcon** [intel/net-test-suites#1]
Thanks for your work on Zephyr IP stack testsuite, trying to play with your setup.

I wondered why with 13+1 tests, running `ttcn3_start test_suite tcp_suite.cfg` reports 15 tests being run. Turns out tcp_tcp_003 is called twice: https://github.com/intel/net-test-suites/blob/master/src/tcp_suite.ttcn#L501

Is it intended? If so, would be nice to get a comment at that line confirming it's intended and explaining why.

**Comment by ozhuraki** [comment]
Thanks for your interest.

It’s just a typo that slipped my attention.
