### ISSUE TITLE
Too big indent in tcp_suite.ttcn

### ISSUE THREAD

**Issue by pfalcon** [intel/net-test-suites#4]
This line: https://github.com/intel/net-test-suites/blob/master/src/tcp_suite.ttcn#L434 seems to have a big indentation, it uses tabs for indentation, perhaps you have small tab size set in your editor, but with 8-char tab, that line's content is too far right, making it hard to read.

**Comment by ozhuraki** [comment]
The indentation on github has been fixed with the commit e41f8c3.
